### ISSUE TITLE
Encountered error while generating package metadata

### ISSUE THREAD

**Issue by randomrushgirl** [MTG/IAM-tutorial-ismir22#14]
Initially I created an environment with `python == 3.7` but the problem was that when installing the requirements, `ipython==8.6.0` which requires python 3.8 or higher. This was clashing with the `"Programming Language :: Python :: 3.7"` in setup.py. 

So I tried creating the environment with python == 3.9 (to be on the safe side) and changed `"Programming Language :: Python :: 3.9" `in setup.py. This results in a new problem:

```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6b/21_q3rhx2r93jzlz797hr55h0000gn/T/pip-install-cmb0ejb2/jsonschema_27666997b8bc42269c5bab40d4278468/setup.py", line 4, in <module>
          from jsonschema import __version__
        File "/private/var/folders/6b/21_q3rhx2r93jzlz797hr55h0000gn/T/pip-install-cmb0ejb2/jsonschema_27666997b8bc42269c5bab40d4278468/jsonschema.py", line 63, in <module>
          class Validator(object):
        File "/private/var/folders/6b/21_q3rhx2r93jzlz797hr55h0000gn/T/pip-install-cmb0ejb2/jsonschema_27666997b8bc42269c5bab40d4278468/jsonschema.py", line 77, in Validator
          u"null" : types.NoneType, u"object" : dict,
      AttributeError: module 'types' has no attribute 'NoneType'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Do we keep python == 3.7 and deprecate the other packages?

**Comment by randomrushgirl** [comment]
Additionally found this documentation that specifies removing support for Python up through 3.7 for the IPython 8.x series:

[https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#removing-support-for-older-python-versions](https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#removing-support-for-older-python-versions)

UPDATE: When running on Google Colab it works with the following versions: 

> python == 3.10.1
> ipython == 7.31.1
